{{- if .Values.IBAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-ibroker-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  TWSUSERID: {{ .Values.TWSUSERID | b64enc | quote }}
  TWSPASSWORD: {{ .Values.TWSPASSWORD | b64enc | quote }}
  FIXUSERID: {{ .Values.FIXUSERID | b64enc | quote }}
  FIXPASSWORD: {{ .Values.FIXPASSWORD | b64enc | quote }}
  {{ if .Values.VNC_PASSWORD }}
  VNC_PASSWORD: {{ .Values.VNC_PASSWORD | b64enc | quote }}
  {{ else }}
  VNC_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}

