apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibgw.fullname" . }}
  labels:
    {{- include "ibgw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.srcport }}
      targetPort: {{ .Values.service.dstport }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "ibgw.selectorLabels" . | nindent 4 }}
