name: Secret Scanning

on:
  push:
    branches:
      - main
      - master
      # Add other branches if needed
    paths:
      - 'path/to/scan/**'
      # Add other paths to scan if needed

  pull_request:
    branches:
      - main
      # Add other branches if needed
    paths:
      - 'path/to/scan/**'
      # Add other paths to scan if needed

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Secret Scanning with max/secret-scan
        id: secret-scan
        uses: max/secret-scan@v1

      - name: Post Scan Output to Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Secret Scan Output:" > scan-output.txt
          echo "${{ steps.secret-scan.outputs.scan_results }}" >> scan-output.txt
          echo "Review and document the secret scan results." >> scan-output.txt
          echo "You can add more information here, such as steps to mitigate any findings." >> scan-output.txt
          echo "" >> scan-output.txt
          echo "Please remember to handle sensitive information securely and follow best practices." >> scan-output.txt
          echo "" >> scan-output.txt
          cat scan-output.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

