name: TruffleHog Secrets Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: ${{ github.head_ref }} # Necessary for pull request workflow trigger

      - name: Install TruffleHog
        run: |
          pip install truffleHog

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: ""

