name: TruffleHog Secrets Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }} # Necessary for pull request workflow trigger

      - name: TruffleHog Scan
        run: |
          pip install truffleHog
          trufflehog --github-actions --regex --entropy=False --max_depth=5

